<?php

class Binance{
    private $api_key = "0b8c8093747e4826923034d83d9abe5a";
    # Get Transaction Info by Transaction Hash https://bsc-mainnet.web3api.com/v1
	public function createAccount(){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $curl = curl_init();

        curl_setopt_array($curl, array(
        CURLOPT_URL => "https://api.blockcypher.com/v1/eth/main/addrs?token=".$this->api_key,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_HTTPHEADER => array(
            "cache-control: no-cache",
            "postman-token: c4a1691f-9221-0334-2625-c9d85a5c36a4"
        ),
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
            $response = array();
        } else {
            $response = json_decode($response,true);
        }
        return $response;
    }
}

